apiVersion: v1

kind: Service 

metadata:
  name: storage-demo
  namespace: session-10

spec:
  type: ClusterIP
  clusterIP: None

  selector:
    app: storage-demo

  ports:
    - name: demo 
      port: 80 