apiVersion: apps/v1

kind: Deployment

metadata:
  name: learning-devops

spec:
  replicas: 3
  selector:
    matchLabels:
      app: learning-devops

  template:
    metadata:
      labels:
        app: learning-devops
    
    spec:
      containers:
        - name: learning-devops
          image: learning-devops/session-08:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: learning-devops-config
                  key: APP_ENV
            
            - name: DEMO_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: learning-devops-secret
                  key: DEMO_API_TOKEN
          
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5

          livenessProbe:
            httpGet: 
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3

