apiVersion: v1
kind: Pod
metadata:
  name: nats-sub-2
  namespace: session-11

spec:
  restartPolicy: Never
  containers:
  - name: nats-sub-2
    image: natsio/nats-box:0.19.7

    command:
      - sh
      - -c
    args: 
      - while true; do sleep 3600; done

    # command:
    #   - nats
    # args: 
    #   - sub
    #   - orders.created
    #   - --server
    #   - nats://nats:4222

    resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 250m
        memory: 128Mi
