apiVersion: apps/v1

kind: StatefulSet

metadata:
  name: rabbitmq
  namespace: session-11

spec:
  serviceName: rabbitmq-headless

  replicas: 1

  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq

    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:4.3.5-management
        imagePullPolicy: IfNotPresent

        ports:
        - name: amqp
          containerPort: 5672
        - name: management
          containerPort: 15672

        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth
              key: username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth
              key: password

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 768Mi

        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq

  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    
    spec:
      accessModes: 
      - ReadWriteOnce

      storageClassName: standard

      resources: 
        requests:
          storage: 1Gi

---
apiVersion: v1

kind: Service

metadata:
  name: rabbitmq-headless
  namespace: session-11

spec:
  selector:
    app: rabbitmq

  clusterIP: None

  ports:
  - name: amqp
    port: 5672
    targetPort: amqp
  - name: management
    port: 15672
    targetPort: management

---
apiVersion: v1

kind: Service

metadata:
  name: rabbitmq
  namespace: session-11

spec:
  type: ClusterIP

  selector:
    app: rabbitmq

  ports:
  - name: amqp
    port: 5672
    targetPort: amqp
  - name: management
    port: 15672
    targetPort: management